import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1 className="text-2xl md:text-7xl text-black md:text-red-100 lg:text-yellow-400 xl:text-teal-300 text-center lg:text-left">Software Engineer Muhammad Nabeel</h1>

      <footer>
        <h6>footer</h6>
      </footer>


    </div>
  )
}
